version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    container_name: my-mailhog
    ports:
      - "1025:1025"  # SMTP порт для отправки почты
      - "8025:8025"  # Веб-интерфейс MailHog
    restart: unless-stopped
